version: "3.3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    links:
      - "mongodb"
    depends_on:
      - mongodb
    command: "npm start"
